### ISSUE TITLE
Setting up Kanban

### ISSUE THREAD

**Issue by AbrahaKahsay** [AbrahaKahsay/final-capstone-backend#18]
**we are a group of four, naming**
 - @lucas-crodrigues 
 - @jevazquezb 
 - @AbrahaKahsay 
 - @aizjicod
 
 link to the [project](https://github.com/AbrahaKahsay/final-capstone-backend/projects/1)

Kanban board screenshot:
![image](https://user-images.githubusercontent.com/84423749/203654321-8fa0e497-98f6-407c-835b-d7dc7cec9f42.png)

**Comment by mcrd25** [comment]
Hi Team, 

In my opinion, you are ready to move on to the next step! ⏭️  


Good luck! 🎉 


Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.

**Comment by mcrd25** [comment]
Hi guys, I accidentally listed the project as "REQUIRES CHANGES". 
You can reference this and ask that the review be changed to APPROVED.

**Comment by Meltrust** [comment]
It's been approved.
